{
 "title": "Traefik Ingress Monitoring",
 "tags": [ "traefik" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "percentiles", "query": "95,99" },
   { "name": "backend", "label": "Backend", "query": "label_values(backend)" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"^$backend$\"}[2m])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Global latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=~\"2..\"}[5m])) by (le))",
     "legendFormat": "Latency over 1 min"
    }
   ]
  },
  {
   "title": "Per node latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=~\"2..\"}[5m])) by (le, instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "HTTP Codes  stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Status codes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"^$backend$\", code=~\"2..\"}[2m])) by (backend)",
     "legendFormat": "2xx - {{ backend }}"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"^$backend$\", code=~\"4..\"}[2m])) by (backend, code)",
     "legendFormat": "{{ code }} - {{ backend }}"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"^$backend$\", code=~\"5..\"}[2m])) by (backend)",
     "legendFormat": "5xx - {{ backend }}"
    }
   ]
  },
  { "title": "Frontends (entrypoints)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.1\", code=\"200\"}[5m])) by (job) / sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  { "title": "Backends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_open_connections{backend=~\"^$backend$\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_bucket{le=\"0.1\", code=\"200\"}[5m])) by (job) / sum(rate(traefik_backend_request_duration_seconds_count{code=\"200\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "Pods ressources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traefik max memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"ingress\", container_name=\"traefik\"})",
       "legendFormat": "Max memory used"
      }
     ]
    },
    {
     "title": "Traefik max CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"ingress\", container_name=\"traefik\"}[2m]))",
       "legendFormat": "Max cpu used"
      }
     ]
    }
   ]
  }
 ]
}