site_name: kloudlib
strict: true
repo_name: place1/kloudlib
repo_url: https://github.com/place1/kloudlib
site_url: https://place1.github.io/kloudlib

docs_dir: src

nav:
  - Home: './index.md'
  - '@kloudlib/nginx-ingress': './packages/modules/__kloudlib_nginx_ingress_.md'
  - '@kloudlib/metal-lb': './packages/modules/__kloudlib_metal_lb_.md'
  - '@kloudlib/cert-manager': './packages/modules/__kloudlib_cert_manager_.md'
  - '@kloudlib/grafana-stack': './packages/modules/__kloudlib_grafana_stack_.md'
  - '@kloudlib/grafana': './packages/modules/__kloudlib_grafana_.md'
  - '@kloudlib/loki': './packages/modules/__kloudlib_loki_.md'
  - '@kloudlib/prometheus': './packages/modules/__kloudlib_prometheus_.md'
  - '@kloudlib/rook-ceph': './packages/modules/__kloudlib_rook_ceph_.md'
  - '@kloudlib/oauth-proxy': './packages/modules/__kloudlib_oauth_proxy_.md'
  - '@kloudlib/minio': './packages/modules/__kloudlib_minio_.md'
  - '@kloudlib/linkerd': './packages/modules/__kloudlib_linkerd_.md'
  - '@kloudlib/prometheus-postgresql-exporter': './packages/modules/__kloudlib_prometheus_postgresql_exporter_.md'
  - '@kloudlib/prometheus-mssql-exporter': './packages/modules/__kloudlib_prometheus_mssql_exporter_.md'
  - '@kloudlib/prometheus-redis-exporter': './packages/modules/__kloudlib_prometheus_redis_exporter_.md'
  - '@kloudlib/prometheus-mongodb-exporter': './packages/modules/__kloudlib_prometheus_mongodb_exporter_.md'
  - '@kloudlib/prometheus-servicebus-exporter': './packages/modules/__kloudlib_prometheus_servicebus_exporter_.md'

theme:
  name: material
  include_sidebar: true
  logo:
    icon: cloud_queue # globe icon
  feature:
    tabs: false
  palette:
    primary: light blue
    accent: teal

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: src
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: " ¶"

plugins:
  - search
